### ISSUE TITLE
addUserAgentInfo

### ISSUE THREAD

**Issue by KeMicrosoft** [Azure/autorest.typescript#386]
After update Swashbuckle.AspNetCore.Swagger to 4.0
The auto rest generate the package with following error 

Property 'addUserAgentInfo' does not exist on type 'AzureMachineLearningDiscoveryClientContext'.

40     this.addUserAgentInfo(`${packageName}/${packageVersion}`);
            ~~~~~~~~~~~~~~~~


[Discovery.EntryPoints.swagger.json.txt](https://github.com/Azure/autorest.typescript/files/2592558/Discovery.EntryPoints.swagger.json.txt)

**Comment by daschult** [comment]
Hi Ke. I just updated the latest tag on the AutoRest TypeScript Generator NPM package. Please try regenerating your package. Your package.json should be updated so that instead of ms-rest-js it now references @azure/ms-rest-js, and instead of ms-rest-azure-js it should now reference @azure/ms-rest-azure-js.
Let me know if this fixes your problem.
If your generation process still runs into issues, you might try running "autorest --reset" and then try regenerating. This command should instruct autorest to look for a new version of the TypeScript generator.

**Comment by KeMicrosoft** [comment]
Hi Dan, I am a bit confused, I tried to update autorest npm, but seems nothing new release?

**Comment by daschult** [comment]
Yes, autorest is an interesting application. The autorest application itself uses several plugin NPM packages that the autorest application manages itself. Just trying to update autorest won't do anything in this scenario. What you need to do is run:
```
autorest --reset
```
This should indicate to autorest that you want to use the latest generators. Once you've done this, then you should be able to regenerate and solve the problem.

**Comment by KeMicrosoft** [comment]
It works!
Thank you!

**Comment by bricejar** [comment]
Another issue is that when I use @azure/ms-rest-js instead of ms-rest-js I get strange type errors on my APIContext class. 


[ts]
Argument of type 'APIsOptions' is not assignable to parameter of type 'ServiceClientOptions'.
  Types of property 'requestPolicyFactories' are incompatible.


For the line  **super(undefined, options)**

` constructor(options?: Models.CyberjusticeAPIsOptions) {
    if (!options) {
      options = {};
    }
    if (!options.userAgent) {
      const defaultUserAgent = msRest.getDefaultUserAgentValue();
      options.userAgent = `${packageName}/${packageVersion} ${defaultUserAgent}`;
    }

    super(undefined, options);`

**Comment by daschult** [comment]
I'd recommend deleting your `node_modules` folder and regenerating your ServiceClient code. This sounds like the previous `ms-rest-js` package might still be slipping into your code somehow.
